version: '3.1'

services:
    mongo:
        image: mongo
        restart: always

    shortlink:
        image: shortlink
        restart: always
        ports:
            - 8001:8001
        environment:
            GIN_MODE: release
